name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Debug Network Connection
        run: |
          curl -I https://www.google.com
          curl -I $SONAR_HOST_URL

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_SCANNER_OPTS: "-Dsonar.ws.timeout=60"

      - name: NPM Install
        run: npm install

      - name: Install Trivy
        run: |
          trivy fs . > trivyfs.txt
